name: 'Build and Deploy to Production'
run-name: ${{ github.actor }} is pushing to production! 🚀

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'lofty-entropy-418903' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  SERVICE: 'indonesiaku' # TODO: update to your service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/396235981273/locations/global/workloadIdentityPools/github/providers/indonesiaku' # TODO: update to your workload identity provider

jobs:
  build:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4
      
      - name: 'Add .env file'
        run: 'echo ${{ secrets.ENV_FILE }} | base64 --decode > .env'
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: 'Authenticate docker with gcloud'
        run: 'gcloud auth configure-docker'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud compute ssh indonesiaku-webserver --region us-central1 --command "DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" && docker pull $DOCKER_TAG && docker run -d -p 3000:3000 $DOCKER_TAG"'